### ISSUE TITLE
when open a task and before click oky if someone select deleat task will delete.

### ISSUE THREAD

**Issue by punsith** [HaikuArchives/TimeTracker#7]
If I open a new task and before click okay select delete task then a task will delete , if this happen as a mistake it isn't good 

![screenshot 111](https://cloud.githubusercontent.com/assets/24215220/21294717/b1fcbb4a-c511-11e6-8d00-c8870ee99ac9.png)
![screenshot 112](https://cloud.githubusercontent.com/assets/24215220/21294718/b1ff0332-c511-11e6-916a-93d2db3692cb.png)
![screenshot 113](https://cloud.githubusercontent.com/assets/24215220/21294719/b205f6f6-c511-11e6-96b4-148f2e761845.png)

**Comment by AkshayAgarwal007** [comment]
Adding of task should be handled in separate window. The user should be able to see the current status of the tasks while creating new ones, but not allowing to delete/reset/start/stop until the new task window is open?

**Comment by humdingerb** [comment]
You've seen all tasks in the main view and decided to create a new one. I'm not sure it's really essential to be able to see the other tasks while creating a new one. Using more windows, makes things only complicated for no real gain.
The simplest solution is to disable the whole "Task" menu while editing or creating a task.
